language: csharp
mono: none
dotnet: 1.0.1
dist: trusty
install:
  - dotnet msbuild /t:Clean
  - dotnet msbuild /t:Restore
script:
  - dotnet msbuild /t:Build
  - dotnet test QueryBuilder.Tests/QueryBuilder.Tests.csproj --no-build
