name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Build QueryBuilder
      run: dotnet build QueryBuilder/QueryBuilder.csproj

    - name: Nightly Builds - Create Packages
      run: dotnet pack QueryBuilder/QueryBuilder.csproj --configuration Release --output="../nuget_packages"

    - name: Nightly Builds - Push Packages
      run: dotnet nuget push nuget_packages/*.nupkg -k "${{ secrets.MYGET }}" -s https://www.myget.org/F/sqlkata/api/v2/package