name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Setup nuget config
      run: sed 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' nuget.config > nuget.config
    - name: Push NuGet packages - Nightly Builds
      run: dotnet pack --configuration Release && dotnet nuget push "bin/Release/querybuilder.1.0.0.nupkg" --source "github"
